### ISSUE TITLE
OFFICIAL: Smartlook plugin

### ISSUE THREAD

**Issue by krsiakdaniel** [lonalore/smartlook#1]
Hi,

we have official Smartlook plugin for WordPress.

https://wordpress.org/plugins/smartlook-visitor-screen-recording/
https://www.smartlook.com/help/wordpress/

~ Daniel 
daniel@smartsupp.com

**Comment by lonalore** [comment]
Thanks, but e107 has nothing to do with WordPress. This integration plugin was made for e107, and not for WordPress.

https://e107.org/plugins/?id=902
